# Generated by Django 4.0.4 on 2023-01-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudoinsta', '0002_alter_post_image_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
